### ISSUE TITLE
Code blocks not being dispayed

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/redoc#39]
In this section: https://docs.reactioncommerce.com/reaction-docs/development/deploying-reaction-using-heroku

There are code blocks like this:
```bash
heroku addons:create mongolab
```
Which do not display at all.

**Comment by zenweasel** [comment]
This applies to all code blocks. The code blocks are being rendered but it looks like something in the style is preventing them from being displayed.

**Comment by jshimko** [comment]
```css
.content-html .section .section-content pre {
  display: none; 
}
```
https://github.com/reactioncommerce/redoc/blob/master/packages/redoc-base-theme/styles/docs.less#L107-L109
